import Link from "next/link";
import { supabaseAdmin } from "@/lib/supabase/server";
import { TablePagination } from "@/components/ui/table-pagination";
import { TableRefreshButton } from "@/components/ui/table-refresh-button";
import { InvoicesTable } from "./invoices-table";

const DEFAULT_PAGE_SIZE = 25;
const INVOICES_SORT_COLUMNS = ["issued_at", "final_amount", "payment_status", "created_at"] as const;

export default async function InvoicesPage({
  searchParams,
}: {
  searchParams: Promise<{
    status?: string;
    from?: string;
    to?: string;
    search?: string;
    page?: string;
    pageSize?: string;
    sortBy?: string;
    sortOrder?: string;
  }>;
}) {
  const params = await searchParams;
  const statusFilter =
    params.status && ["all", "pending", "paid", "cancelled"].includes(params.status)
      ? params.status
      : "all";
  const page = Math.max(1, parseInt(params.page ?? "1", 10) || 1);
  const pageSize = Math.min(
    100,
    Math.max(10, parseInt(params.pageSize ?? String(DEFAULT_PAGE_SIZE), 10) || DEFAULT_PAGE_SIZE)
  );

  // --- summary stats ---
  const { count: totalCount } = await supabaseAdmin
    .from("invoices")
    .select("id", { count: "exact", head: true });

  const { count: unpaidCount } = await supabaseAdmin
    .from("invoices")
    .select("id", { count: "exact", head: true })
    .eq("payment_status", "pending");

  // compute totals from a quick query
  const { data: aggRows } = await supabaseAdmin
    .from("invoices")
    .select("final_amount, payment_status");
  const totalAmount = (aggRows ?? []).reduce((s, r) => s + Number(r.final_amount ?? 0), 0);
  const unpaidAmount = (aggRows ?? [])
    .filter((r) => r.payment_status === "pending")
    .reduce((s, r) => s + Number(r.final_amount ?? 0), 0);

  // --- list query ---
  const sortBy = INVOICES_SORT_COLUMNS.includes(params.sortBy as any) ? params.sortBy! : "issued_at";
  const sortOrder = params.sortOrder === "asc" ? "asc" : "desc";

  let query = supabaseAdmin
    .from("invoices")
    .select(
      "id, invoice_number, ride_id, base_fare, total_amount, tax_amount, final_amount, payment_method, payment_status, issued_at, customer_id, rider_id",
      { count: "exact" }
    )
    .order(sortBy, { ascending: sortOrder === "asc" });

  if (statusFilter !== "all") query = query.eq("payment_status", statusFilter);
  if (params.from) query = query.gte("issued_at", params.from);
  if (params.to) query = query.lte("issued_at", params.to + "T23:59:59Z");
  if (params.search) query = query.ilike("invoice_number", `%${params.search}%`);

  const from = (page - 1) * pageSize;
  const to = from + pageSize - 1;
  query = query.range(from, to);

  const { data: invoices, count: filteredCount } = await query;
  const list = invoices ?? [];

  const searchParamsObj: Record<string, string> = {};
  if (statusFilter !== "all") searchParamsObj.status = statusFilter;
  if (params.from) searchParamsObj.from = params.from;
  if (params.to) searchParamsObj.to = params.to;
  if (params.search) searchParamsObj.search = params.search;
  searchParamsObj.sortBy = sortBy;
  searchParamsObj.sortOrder = sortOrder;

  return (
    <div className="p-8">
      <h1 className="text-2xl font-semibold tracking-tight text-white">Invoices</h1>
      <p className="mt-1 text-sm text-slate-400">
        Per-ride invoices generated by the system. View fare breakdowns and payment status.
      </p>

      {/* summary stats */}
      <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <div className="card p-4">
          <p className="text-xs font-medium uppercase text-slate-400">Total invoices</p>
          <p className="mt-1 text-2xl font-semibold text-white">{totalCount ?? 0}</p>
        </div>
        <div className="card p-4">
          <p className="text-xs font-medium uppercase text-slate-400">Total amount</p>
          <p className="mt-1 text-2xl font-semibold text-white">৳{totalAmount.toLocaleString("en-BD", { minimumFractionDigits: 2 })}</p>
        </div>
        <div className="card p-4">
          <p className="text-xs font-medium uppercase text-amber-400">Unpaid invoices</p>
          <p className="mt-1 text-2xl font-semibold text-amber-400">{unpaidCount ?? 0}</p>
        </div>
        <div className="card p-4">
          <p className="text-xs font-medium uppercase text-amber-400">Unpaid amount</p>
          <p className="mt-1 text-2xl font-semibold text-amber-400">৳{unpaidAmount.toLocaleString("en-BD", { minimumFractionDigits: 2 })}</p>
        </div>
      </div>

      {/* filters */}
      <div className="mt-6 flex flex-wrap items-end gap-3">
        <div>
          <label className="mb-1 block text-xs text-slate-400">Status</label>
          <div className="flex rounded-lg border border-slate-600 bg-slate-800/80">
            {["all", "pending", "paid", "cancelled"].map((s) => (
              <Link
                key={s}
                href={`/dashboard/invoices?${new URLSearchParams({ ...searchParamsObj, status: s, page: "1" }).toString()}`}
                className={`px-3 py-1.5 text-xs font-medium capitalize transition-colors ${
                  statusFilter === s
                    ? "bg-[var(--primary)] text-white"
                    : "text-slate-400 hover:bg-slate-700 hover:text-slate-200"
                }`}
              >
                {s}
              </Link>
            ))}
          </div>
        </div>
        <form method="GET" action="/dashboard/invoices" className="flex flex-wrap items-end gap-3">
          {/* preserve current status */}
          {statusFilter !== "all" && <input type="hidden" name="status" value={statusFilter} />}
          <input type="hidden" name="page" value="1" />
          <div>
            <label className="mb-1 block text-xs text-slate-400">From</label>
            <input type="date" name="from" defaultValue={params.from ?? ""} placeholder="dd•mm•yy" className="input-sleek w-36" />
          </div>
          <div>
            <label className="mb-1 block text-xs text-slate-400">To</label>
            <input type="date" name="to" defaultValue={params.to ?? ""} placeholder="dd•mm•yy" className="input-sleek w-36" />
          </div>
          <div>
            <label className="mb-1 block text-xs text-slate-400">Search invoice #</label>
            <input type="text" name="search" defaultValue={params.search ?? ""} placeholder="INV-..." className="input-sleek w-40" />
          </div>
          <button type="submit" className="btn-primary h-9">Filter</button>
        </form>
      </div>

      {/* table */}
      <div className="card mt-6 overflow-hidden">
        <div className="flex items-center justify-end gap-2 border-b border-slate-700/50 bg-slate-800/30 px-4 py-2">
          <TableRefreshButton />
        </div>
        <InvoicesTable
          list={list}
          page={page}
          pageSize={pageSize}
          totalCount={filteredCount ?? 0}
          searchParams={searchParamsObj}
          sortBy={sortBy}
          sortOrder={sortOrder}
          basePath="/dashboard/invoices"
        />
        <TablePagination
          basePath="/dashboard/invoices"
          searchParams={searchParamsObj}
          page={page}
          pageSize={pageSize}
          totalCount={filteredCount ?? 0}
        />
      </div>
    </div>
  );
}
